language: node_js
before_install:
  - npm i -g npm@5.5.1
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
